{
 "title": "TechM_Dashboard",
 "description": "Visualization Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TechM - Real-Time logging Dashboard ( General View )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Error per App (Overall)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\nId as AppID,\n(COUNT(CASE WHEN messageType = 'error' THEN 1 END) * 100.0 / COUNT(*)) AS error_percentage\nFROM logs_messages_tb\nGROUP BY Id",
     "rawQueryText": "SELECT\nId as AppID,\n(COUNT(CASE WHEN messageType = 'error' THEN 1 END) * 100.0 / COUNT(*)) AS error_percentage\nFROM logs_messages_tb\nGROUP BY Id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Errors of Today - ${__from:date:YYYY-MM-DD} ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\n    Id as AppID,\n    (COUNT(CASE WHEN messageType = 'error' THEN 1 END) * 100.0 / COUNT(*)) AS error_percentage\nFROM\n    logs_messages_tb\nWHERE\n    SUBSTR(dateLog, 7, 4) || '-' || SUBSTR(dateLog, 4, 2) || '-' || SUBSTR(dateLog, 1, 2) = DATE('now')\nGROUP BY\n    Id;\n",
     "rawQueryText": "SELECT\n    Id as AppID,\n    (COUNT(CASE WHEN messageType = 'error' THEN 1 END) * 100.0 / COUNT(*)) AS error_percentage\nFROM\n    logs_messages_tb\nWHERE\n    SUBSTR(dateLog, 7, 4) || '-' || SUBSTR(dateLog, 4, 2) || '-' || SUBSTR(dateLog, 1, 2) = DATE('now')\nGROUP BY\n    Id;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "App Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nId as AppID,\nCOUNT(*) AS log_count\n FROM logs_messages_tb\nGROUP BY Id",
     "rawQueryText": "SELECT\nId as AppID,\nCOUNT(*) AS log_count\n FROM logs_messages_tb\nGROUP BY Id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Application Count Breakdown",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT Id,\nCOUNT(CASE WHEN messageType = 'error' THEN 1 END) AS Error_Count,\nCOUNT(CASE WHEN messageType = 'info' THEN 1 END) AS Info_Count,\nCOUNT(CASE WHEN messageType = 'create' THEN 1 END) AS Create_Count,\nCOUNT(CASE WHEN messageType = 'delete' THEN 1 END) AS Delete_Count,\nCOUNT(CASE WHEN messageType NOT IN ('error', 'info', 'create', 'delete') THEN 1 ELSE NULL END) AS Other_Count\nFROM logs_messages_tb\nGROUP BY Id",
     "rawQueryText": "SELECT Id,\nCOUNT(CASE WHEN messageType = 'error' THEN 1 END) AS Error_Count,\nCOUNT(CASE WHEN messageType = 'info' THEN 1 END) AS Info_Count,\nCOUNT(CASE WHEN messageType = 'create' THEN 1 END) AS Create_Count,\nCOUNT(CASE WHEN messageType = 'delete' THEN 1 END) AS Delete_Count,\nCOUNT(CASE WHEN messageType NOT IN ('error', 'info', 'create', 'delete') THEN 1 ELSE NULL END) AS Other_Count\nFROM logs_messages_tb\nGROUP BY Id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unclassified Logs Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "queryText": "-- SELECT\n--     Id as AppID,\n--     (COUNT(CASE WHEN messageType NOT IN ('error', 'info', 'create', 'delete') THEN 1 END) / COUNT(*)) AS Other\n-- FROM\n--     logs_messages_tb\n-- WHERE\n--     SUBSTR(dateLog, 7, 4) || '-' || SUBSTR(dateLog, 4, 2) || '-' || SUBSTR(dateLog, 1, 2) = DATE('now')\n-- GROUP BY\n--     Id;\n\nSELECT\nId as AppID,\n(COUNT(CASE WHEN messageType NOT IN ('error', 'info', 'create', 'delete') THEN 1 END) ) AS Other\nFROM logs_messages_tb\nGROUP BY Id",
     "rawQueryText": "-- SELECT\n--     Id as AppID,\n--     (COUNT(CASE WHEN messageType NOT IN ('error', 'info', 'create', 'delete') THEN 1 END) / COUNT(*)) AS Other\n-- FROM\n--     logs_messages_tb\n-- WHERE\n--     SUBSTR(dateLog, 7, 4) || '-' || SUBSTR(dateLog, 4, 2) || '-' || SUBSTR(dateLog, 1, 2) = DATE('now')\n-- GROUP BY\n--     Id;\n\nSELECT\nId as AppID,\n(COUNT(CASE WHEN messageType NOT IN ('error', 'info', 'create', 'delete') THEN 1 END) ) AS Other\nFROM logs_messages_tb\nGROUP BY Id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Application Logs Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT \n    id as AppID, \n    dateLog as Data, \n    timeLog as Time,\n    message as Message, \n    Upper(messageType) as Type \nFROM \n    logs_messages_tb \nORDER BY \n    SUBSTR(dateLog, 7, 4) || '-' || SUBSTR(dateLog, 4, 2) || '-' || SUBSTR(dateLog, 1, 2) || ' ' || timeLog DESC;\n",
     "rawQueryText": "SELECT \n    id as AppID, \n    dateLog as Data, \n    timeLog as Time,\n    message as Message, \n    Upper(messageType) as Type \nFROM \n    logs_messages_tb \nORDER BY \n    SUBSTR(dateLog, 7, 4) || '-' || SUBSTR(dateLog, 4, 2) || '-' || SUBSTR(dateLog, 1, 2) || ' ' || timeLog DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}